### ISSUE TITLE
recurrence error

### ISSUE THREAD

**Issue by eouia** [mifi/ical-expander#10]
Hello mifi.
I have a trouble with this iCal to parse.
`Same occurrence found twice, protecting you from death by recursion` error occurs.
But I cannot find what is wrong.

iCal URL : 
https://calendar.google.com/calendar/ical/giuseppe.aprile%40gmail.com/private-654bc306d73fde5ca6f312c134386960/basic.ics

Tried code :
```
var iCalData = ... content text of given URL
icalExpander = new IcalExpander({ics:iCalData, maxIterations: 10})
```

**Comment by mifi** [comment]
Maybe related to this? https://github.com/mozilla-comm/ical.js/issues/292

**Comment by eouia** [comment]
Thanks for your reply. As you wrote, it seems so.
So... it was not fixed yet? The issue was closed, but I cannot find how to do with your module.

**Comment by mifi** [comment]
Maybe you can post in that issue? with your ICS. I don't know the inner workings of ical.js (which this library depends on)

**Comment by eouia** [comment]
Thanks for your suggestion. I'll ask them.
