### ISSUE TITLE
"between" for modified recurring events doesn't work as expected

### ISSUE THREAD

**Issue by andeee** [mifi/ical-expander#14]
Hi Mikael,

in the test ics file `icaljs-issue-285.ics` there is a recurring event, where one occurence is modified not to be on 17.01.2017 but on 18.01.2017. 
using your library
```javascript
new IcalExpander({ ics: icaljsIssue285 })
    .between(new Date('2017-01-18T00:00:00.000Z'), new Date('2017-01-19T00:00:00.000Z'))
```
returns neither a occurence nor an event - I would expect the library to return the modified recurrence here.

I have prepared 2 branches on my fork, each one should fix the issue - but I would like to discuss the changes and options with you first.
* Option 1: andeee/ical-expander@be5e71961e4728562dcc0d3b0546310d0abb8fc1 Reread the start/endTime when checking the modified recurrence
* Option 2: andeee/ical-expander@0de32aa855ad756863a324bdaeae887e1f8955bf Upgrade to ical.js 1.3.0
The issue with Option 2 is that the behaviour changed in ical.js 1.3.0 so the modified reccurence doesn't get into the events array but in the occurrences array with the modified start/end date - you saw the effect of it in #11
To restore the behaviour of ical.js 1.2.2 for ical-expander there would be still something to do.

I'm looking forward to your reply!

**Comment by mifi** [comment]
Hey, I'm sorry for the slow reply, I forgot about this one. I think upgrading to 1.3.0 is the right way to go. I haven't used ical-expander in a while, so I don't remember the details now, but if you agree that option 2 is the right way, then i'm happy to merge a PR for that fix.

**Comment by radarfox** [comment]
Hello,

I'm confirming this problem. `ical-expander` in versions 2.0 and 2.1 doesn't work with modified occurrences of recurring events. It simply ignores them.

I have used the second option suggested by @andeee and everything works just fine. I have enforced a new version in package.json, like this:

```json
{
  "resolutions": {
    "ical.js": "^1.4.0"
  }
}
```

Both 1.3 and 1.4 of `ical.js` works fine.

Can you please fix this, as it should be super easy, and @andeee even prepared the unit tests for it.

**Comment by andeee** [comment]
@mifi - Hi, no problem - I just created a pull request for option 2.
