### ISSUE TITLE
found some bugs

### ISSUE THREAD

**Issue by kelunyang** [mifi/ical-expander#4]
Hello, I'm using this project in my node.js app, thanks to this project, it's really save my time.
But I found one bug and one mistake in example code:

Bug:
parameter after and before in between function are string, calling getTime() cause exception

Example code:
since parse() use opt.ics property, maybe the example code should be new IcalExpander({ ics: ics, maxIterations: 100 }); the ics: is missing

thank!

**Comment by mifi** [comment]
Hi. Have you tried with just `ics` ? It should work fine too because it's valid ES6

**Comment by mifi** [comment]
I just tried the example and it's working fine with node 4

**Comment by kelunyang** [comment]
sorry, my mistake, use just ics will be fine. ( I use another variable name )
should I have to patch getTime() issue by myself?
thanks!

**Comment by mifi** [comment]
I don't understand the problem with getTime(). Do you have an example?

**Comment by kelunyang** [comment]
ok, when I parse my own ics file on outlook.com ( [this one](https://outlook.live.com/owa//calendar/aebbea8e-614e-496f-bdef-c0738ae1cf5f/de716edc-68ae-4a6b-9d32-51f5a3823181/cid-C836A59DFA673571/calendar.ics) )

both after and before in between() are string, for example: after = "2017-10-17T14:19:29.576Z", before = "2017-10-31T14:19:29.576Z"
when I call getTime(), it returns "Uncaught TypeError: after.getTime is not a function"

so I patched index.js myself, casting after and before to Date object, otherwise getTime() in between() won't work

**Comment by mifi** [comment]
You want after and before arguments to accept either string OR Date objects? I don't see why that's necessary

**Comment by kelunyang** [comment]
I just want to tranfer date to between(), string or date doesn't matter,
but, for example, in line 77 - 78 in index.js, you wrote
`(!before || endTime <= before.getTime()) &&
              (!after || startTime >= after.getTime())`
since before and after are string, they don't have such methd: getTime()
in order to use getTime(), I think you might have to convert before and after into a date object

**Comment by dave-irvine** [comment]
@kelunyang Show a full code sample of how you are using the library.

The `between()` function takes two Date objects as parameters. If you are passing strings to this function then you are using the library incorrectly.

**Comment by kelunyang** [comment]
Ahhhh... thank @dave-irvine  , it's my mistake, after I casting my parameter to Date, this library works will!
Thanks for your great works!

**Comment by dave-irvine** [comment]
@mifi Looks like you can close this one :)
